### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by hannesm** [roburio/albatross#16]
- [x] block device handling (see #19)
- [ ] revocation: being able to upload a CRL which then kills potentially running vms that are revoked now; appropriate CA utilities for this (not mandatory)
- [ ] `vmmd_influx` over TLS (not mandatory)
- [x] reporting exit code properly in `vmmc_*` (enabled via tls.0.9.3) see #31
- [x] statistics (at least interface stats) for Linux (see #2, solved in #44 #45)
- [x] memory (kinfo_proc) statistics on FreeBSD (stack, data, resident in pages)
- [x] document / generate ASN.1 grammar (done in #48)
- [x] shellcheck packaging scripts
- [x] FreeBSD provide `vmmd_tls` startup script
- [x] linux systemd init scripts (#25)
- [ ] use strings for sending data (not mandaory)
- [x] poper teardown of vmmd (kill all VMs)

**Comment by hannesm** [comment]
now an initial 1.0.0 is released. I'll open specific issues for the leftover.
